Deepgram: Log Class Reference
Log Class Reference
Static Public Member Functions
static Serilog.ILogger Initialize (LogLevel level=LogLevel.Information, string? filename="log.txt")
Initializes the logger with the specified log level and filename.
static Serilog.ILogger GetLogger ()
Gets the logger instance
static void Verbose (string identifier, string trace)
Logs a verbose message
static void Debug (string identifier, string trace)
Logs a debug message
static void Information (string identifier, string trace)
Logs an information message
static void Warning (string identifier, string trace)
Logs an warning message
static void Error (string identifier, string trace)
Logs an error message
static void Fatal (string identifier, string trace)
Logs an fatal message
Detailed Description
Definition at line 10 of file Log.cs.
Member Function Documentation
Debug()
static void Log.Debug (string identifier, string trace) inline static
Logs a debug message
Definition at line 72 of file Log.cs.
     {
         GetLogger().Debug($"{identifier}: {trace}");
     }
Referenced by Client.Client(), Client.Connect(), DeepgramHttpClientOptions.DeepgramHttpClientOptions(), DeepgramWsClientOptions.DeepgramWsClientOptions(), AbstractRestClient.DeleteAsync< S, T >(), AbstractRestClient.DeleteAsync< T >(), AbstractRestClient.GetAsync< S, T >(), AbstractRestClient.GetAsync< T >(), AbstractRestClient.PatchAsync< S, T >(), AbstractRestClient.PostAsync< R, S, T >(), AbstractRestClient.PostAsync< S, T >(), AbstractRestClient.PostRetrieveLocalFileAsync< R, S, T >(), AbstractRestClient.PutAsync< S, T >(), and Client.Stop().
Error()
static void Log.Error (string identifier, string trace) inline static
Logs an error message
Definition at line 96 of file Log.cs.
     {
         GetLogger().Error($"{identifier}: {trace}");
     }
Referenced by Client.Connect(), DeepgramHttpClientOptions.DeepgramHttpClientOptions(), DeepgramWsClientOptions.DeepgramWsClientOptions(), AbstractRestClient.DeleteAsync< S, T >(), AbstractRestClient.DeleteAsync< T >(), AbstractRestClient.GetAsync< S, T >(), AbstractRestClient.GetAsync< T >(), AbstractRestClient.PatchAsync< S, T >(), AbstractRestClient.PostAsync< R, S, T >(), AbstractRestClient.PostAsync< S, T >(), AbstractRestClient.PostRetrieveLocalFileAsync< R, S, T >(), AbstractRestClient.PutAsync< S, T >(), and Client.Stop().
Fatal()
static void Log.Fatal (string identifier, string trace) inline static
Logs an fatal message
Definition at line 104 of file Log.cs.
     {
         GetLogger().Fatal($"{identifier}: {trace}");
     }
GetLogger()
static Serilog.ILogger Log.GetLogger () inline static
Gets the logger instance
Definition at line 52 of file Log.cs.
     {
         if (instance == null)
         {
             return Initialize();
         }
         return instance;
     }
Referenced by Debug(), Error(), Fatal(), Information(), Verbose(), and Warning().
Information()
static void Log.Information (string identifier, string trace) inline static
Logs an information message
Definition at line 80 of file Log.cs.
     {
         GetLogger().Information($"{identifier}: {trace}");
     }
Referenced by Client.Connect(), DeepgramHttpClientOptions.DeepgramHttpClientOptions(), DeepgramWsClientOptions.DeepgramWsClientOptions(), AbstractRestClient.DeleteAsync< S, T >(), AbstractRestClient.DeleteAsync< T >(), AbstractRestClient.GetAsync< S, T >(), AbstractRestClient.GetAsync< T >(), AbstractRestClient.PatchAsync< S, T >(), AbstractRestClient.PostAsync< R, S, T >(), AbstractRestClient.PostAsync< S, T >(), AbstractRestClient.PostRetrieveLocalFileAsync< R, S, T >(), AbstractRestClient.PutAsync< S, T >(), and Client.Stop().
Initialize()
static Serilog.ILogger Log.Initialize (LogLevel level = LogLevel.Information, string? filename = "log.txt") inline static
Initializes the logger with the specified log level and filename.
Definition at line 23 of file Log.cs.
     {
         if (level == LogLevel.Disable)
         {
             instance = new LoggerConfiguration()
                 .MinimumLevel.Is(((LogEventLevel)1 + (int)LogEventLevel.Fatal))
                 .WriteTo.Console(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}")
                 .CreateLogger();
             return instance;
         }
         if (filename != null)
         {
             instance = new LoggerConfiguration()
                 .MinimumLevel.Is((LogEventLevel) level)
                 .WriteTo.Console(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}")
                 .WriteTo.File(filename, outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}")
                 .CreateLogger();
             return instance;
         }
         instance = new LoggerConfiguration()
             .MinimumLevel.Is((LogEventLevel)level)
             .WriteTo.Console(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}")
             .CreateLogger();
         return instance;
     }
Referenced by GetLogger(), and Library.Initialize().
Verbose()
static void Log.Verbose (string identifier, string trace) inline static
Logs a verbose message
Definition at line 64 of file Log.cs.
     {
         GetLogger().Verbose($"{identifier}: {trace}");
     }
Referenced by Client.Client(), Client.Connect(), DeepgramHttpClientOptions.DeepgramHttpClientOptions(), DeepgramWsClientOptions.DeepgramWsClientOptions(), AbstractRestClient.DeleteAsync< S, T >(), AbstractRestClient.DeleteAsync< T >(), AbstractRestClient.GetAsync< S, T >(), AbstractRestClient.GetAsync< T >(), AbstractRestClient.PatchAsync< S, T >(), AbstractRestClient.PostAsync< R, S, T >(), AbstractRestClient.PostAsync< S, T >(), AbstractRestClient.PostRetrieveLocalFileAsync< R, S, T >(), AbstractRestClient.PutAsync< S, T >(), Client.SendBinaryImmediately(), Client.SendMessageImmediately(), and Client.Stop().
Warning()
static void Log.Warning (string identifier, string trace) inline static
Logs an warning message
Definition at line 88 of file Log.cs.
     {
         GetLogger().Warning($"{identifier}: {trace}");
     }
Referenced by DeepgramHttpClientOptions.DeepgramHttpClientOptions(), and DeepgramWsClientOptions.DeepgramWsClientOptions().
The documentation for this class was generated from the following file:
Deepgram/Logger/Log.cs