name: Development Releases

on:
    push:
      branches:
        - "!not_activated_on_branches!*"
      tags:
        - "[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
        - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
        - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
        - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Update Version in __init__.py
        run: echo "hello"