name: Doxygen

on:
  push:
    branches:
      - "!not_activated_on_branches!*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code from main branch        
          uses: actions/checkout@v3
          with:
            ref: main
            repository: ${{ github.repository }}

        - name: Get the current tag name
          run: echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"

        # New Step: Extracting Major Version Number
        - name: Set the current major version
          run: echo "MAJOR_VERSION=$(echo $TAG_NAME | cut -d '.' -f 1)" >> "$GITHUB_ENV" # This extracts the major version assuming a 'vX.Y.Z' format

        - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: gh-pages
              folder: docs
              config_file: Doxyfile

        - name: Print the GitHub Pages URL for the current tag
          run: |
            echo "Documentation URL for $TAG_NAME: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/index.html"
      